### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by espenhgn** [CINPLA/expipe#13]
Trying to import expipe on Python 2.7, I get:
```
Espens-MacBook-Pro:expipe ehagen$ python -c "import expipe"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "expipe/__init__.py", line 4, in <module>
    from .config import settings, configure, ensure_testing
  File "expipe/config.py", line 100, in <module>
    except FileNotFoundError:
````

You should consider incorporating 2.7 support (including travisCI tests w. 2.7 as well) as far from everyone have made a transition to Python 3.x

**Comment by dragly** [comment]
We have chosen to only target Python 3 to reduce the amount of work and testing needed to be compatible with both 2 and 3. It has been especially important to reduce the extra overhead in early development of Expipe. Considering that other big projects, like Django, are now dropping support for Python 2, I still think we should focus our efforts on Python 3.

That being said, we are open to include Python 2 support if anyone wants to add and maintain it as we move forward. Adding it should be fairly easy with a couple of `future` imports. This might also be necessary in our lab because some packages we use are not ported to Python 3 yet. However, if anyone wants to spend time on porting Expipe to Python 2 because of an old, yet important package, please consider porting said package to Python 3. It might be a better investment in the long run.
